<a href="https://colab.research.google.com/github/aida-am247/Machine-Learning/blob/master/Mini-Project/ML_miniProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [95]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df_train = pd.read_csv('/content/sample_data/mnist_train_small.csv')
df_test = pd.read_csv('/content/sample_data/mnist_test.csv')

df_train = df_train.head(4800)
x_tr = df_train.to_numpy()
y_train = x_tr[:, 0]
x_train = x_tr[:, 1:]

df_valid = df_train.head(1200)
x_va = df_valid.to_numpy()
y_valid = x_tr[:, 0]
x_valid = x_tr[:, 1:]

df_test = df_test.head(1200)
x_te = df_test.to_numpy()
y_test = x_te[:, 0]
x_test = x_te[:, 1:]

#feature scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

#Linear Regression

In [96]:
from sklearn.linear_model import LinearRegression
clf = LinearRegression(fit_intercept=True, normalize=True)
clf.fit(x_train, y_train)
print(clf.score(x_valid, y_valid))
print(clf.score(x_test, y_test))

-2.3913502835549837e+24
-5.742117855700082e+24


#Logistic Regression

In [97]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(class_weight='balanced')
clf.fit(x_train, y_train)
print(clf.score(x_valid, y_valid))
print(clf.score(x_test, y_test))

0.7954166666666667
0.8725


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


#KNN

In [98]:
from sklearn.neighbors import KNeighborsClassifier
for i in range(2,15):
  clf = KNeighborsClassifier(n_neighbors=i)
  clf.fit(x_train, y_train)
  print("n neighbors = {}\tvalidation score:{}\ttest score:{}".format(i,clf.score(x_valid, y_valid), clf.score(x_test, y_test)))

n neighbors = 2	validation score:0.8391666666666666	test score:0.8541666666666666
n neighbors = 3	validation score:0.859375	test score:0.8625
n neighbors = 4	validation score:0.8445833333333334	test score:0.8575
n neighbors = 5	validation score:0.8522916666666667	test score:0.87
n neighbors = 6	validation score:0.8514583333333333	test score:0.8741666666666666
n neighbors = 7	validation score:0.8508333333333333	test score:0.8725
n neighbors = 8	validation score:0.8420833333333333	test score:0.8641666666666666
n neighbors = 9	validation score:0.8414583333333333	test score:0.8666666666666667
n neighbors = 10	validation score:0.8404166666666667	test score:0.8641666666666666
n neighbors = 11	validation score:0.84	test score:0.8608333333333333
n neighbors = 12	validation score:0.84	test score:0.8616666666666667
n neighbors = 13	validation score:0.8354166666666667	test score:0.8583333333333333
n neighbors = 14	validation score:0.8347916666666667	test score:0.8591666666666666


#SVM

In [100]:
from sklearn.svm import SVC
clf = SVC(C=0.5, gamma='auto')
clf.fit(x_train, y_train)
print(clf.score(x_valid, y_valid))
print(clf.score(x_test, y_test))

0.10145833333333333
0.8933333333333333


#Decision Tree

In [101]:
from sklearn.tree import DecisionTreeClassifier
max_acc = 0
best_ms = 2
for i in range(2, 100):
  clf = DecisionTreeClassifier(min_samples_split=i, criterion='entropy')
  clf.fit(x_train, y_train)
  test_score = clf.score(x_test, y_test)
  valid_score = clf.score(x_valid, y_valid)
  if test_score>max_acc:
    max_acc = test_score
    best_ms = i
clf = DecisionTreeClassifier(min_samples_split=best_ms, criterion='entropy')
clf.fit(x_train, y_train)
test_score = clf.score(x_test, y_test)
valid_score = clf.score(x_valid, y_valid)
print("min samples: {}\tvalidation acc: {}\ttest acc: {}".format(best_ms,valid_score, test_score))

min samples: 4	validation acc: 0.1525	test acc: 0.26666666666666666


#Random Forest

In [102]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=38)
clf.fit(x_train, y_train)
print(clf.score(x_valid, y_valid))
print(clf.score(x_test, y_test))

0.26729166666666665
0.6208333333333333


#Neural Network

In [103]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier()
clf.fit(x_train, y_train)
print(clf.score(x_valid, y_valid))
print(clf.score(x_test, y_test))

0.8472916666666667
0.9175


In [104]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix
y_pre_valid = clf.predict(x_valid)
y_pre_test = clf.predict(x_test)

In [105]:
acc_valid = accuracy_score(y_valid, y_pre_valid)
acc_test = accuracy_score(y_test, y_pre_test)
recall_valid = recall_score(y_valid, y_pre_valid, average='weighted')
recall_test = recall_score(y_test, y_pre_test, average='weighted')
precision_valid = precision_score(y_valid, y_pre_valid, average='weighted')
precision_test = precision_score(y_test, y_pre_test, average='weighted')
confusion_valid = confusion_matrix(y_valid, y_pre_valid)
confusion_test = confusion_matrix(y_test, y_pre_test)

print("---validation data---")
print("accuracy:{}\trecall:{}\tprecision:{}".format(acc_valid, recall_valid, precision_valid))
print("confusion matrix:")
print(confusion_valid)
print("---test data---")
print("accuracy:{}\trecall:{}\tprecision:{}".format(acc_test, recall_test, precision_test))
print("confusion matrix:")
print(confusion_test)

---validation data---
accuracy:0.8472916666666667	recall:0.8472916666666667	precision:0.9023613061481941
confusion matrix:
[[476   0   0   0   0   0   1   0   4   0]
 [  0 245   7  43   0   0   1   9 235   1]
 [  1   0 446   4   6   0   6   1  23   0]
 [  2   0   2 451   0   4   0   0  12   0]
 [  0   0   0   1 383   0   3   1  29  27]
 [  8   0   4   7   2 252   9   0 130   5]
 [  2   0   0   0   2   0 462   0   9   0]
 [  4   0   3  21  10   1   0 437  19  24]
 [  0   0   0   1   0   0   0   0 463   0]
 [  1   0   0   4   0   0   0   2  42 452]]
---test data---
accuracy:0.9175	recall:0.9175	precision:0.9187308397262622
confusion matrix:
[[ 99   0   0   0   0   0   1   0   0   0]
 [  0 147   0   0   0   0   1   0   0   0]
 [  1   1 121   2   0   0   0   4   4   1]
 [  0   1   1 108   0   7   1   2   4   2]
 [  0   0   2   0 123   0   3   1   0   7]
 [  2   0   0   0   0  97   2   2   4   0]
 [  3   1   0   0   1   1  98   0   1   0]
 [  0   0   1   2   0   0   0 110   0  10]
 [  2   0